# Test that the Dockerfile builds successfully.
# This does not test that the newest Python changes work, since the package is installed from pypi.

on:
  push:
    branches:
      - main
      - develop
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/build-docker.yml
  pull_request:
    branches:
      - main
      - develop
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/build-docker.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
